CREATE TABLE "FILE_SUMMARY"("FILE_NAME" VARCHAR2(255) NOT NULL,"IDENTIFIER" NUMBER(38) NOT NULL,"FILE_TYPE" VARCHAR2(255),"USAGE_TYPE" VARCHAR2(255),"SENDER" VARCHAR2(255),"RECEIVER" VARCHAR2(255),"TOTAL_RECORDS_DCH" NUMBER(38),"TOTAL_VOLUME_DCH" NUMBER(38),"TOTAL_CHARGES_DCH" NUMBER(38,2),"TOTAL_RECORDS" NUMBER(38),"TOTAL_VOLUME" NUMBER(38),"TOTAL_CHARGES" NUMBER(38,2),"DROPPED_RECORDS" NUMBER(38),"DUPLICATES" NUMBER(38),"TC_SEND" NUMBER(38),"DROPPED_TC" NUMBER(38),"REJECTED_COUNT" NUMBER(38),"REJECTED_CHARGES" NUMBER(38,2),"DROPPED_APRM" NUMBER(10),"DROPPED_APRM_CHARGES" NUMBER(38,2),"APRM_DIFFERENCE" NUMBER(38),"APRM_TOTAL_RECORDS" NUMBER(38),"APRM_TOTAL_CHARGES" NUMBER(38,2),"PROCESS_DATE" DATE,"FILE_NAME_DCH" VARCHAR2(100))
CREATE TABLE "REJECTED_RECORDS"("FILE_NAME" VARCHAR2(255),"ERROR_CODE" VARCHAR2(255),"ERROR_TYPE" VARCHAR2(255),"ERROR_DESCRIPTION" VARCHAR2(255),"TOTAL_CHARGE" NUMBER(38,2))
CREATE TABLE "APRM"("CARRIER_CODE" VARCHAR2(255),"MARKET_CODE" VARCHAR2(255),"FILE_TYPE" VARCHAR2(255),"BP_START_DATE" DATE NOT NULL,"DATE_PROCESSED" DATE,"CLEARINGHOUSE" VARCHAR2(255),"RECORD_COUNT" NUMBER(38),"TOTAL_VOLUME" NUMBER(38),"TOTAL_CHARGES" NUMBER(38,2),"USAGE_TYPE" VARCHAR2(100),"RECORD_COUNT_DCH" NUMBER(38),"TOTAL_VOLUME_DCH" NUMBER(38),"TOTAL_CHARGES_DCH" NUMBER(38,2),"SERVE_BID" VARCHAR2(100))
CREATE TABLE "SAP_STAGING"("MONTH_TYPE" VARCHAR2(32),"DOC_HEADER" VARCHAR2(32),"TECHNOLOGY" VARCHAR2(32),"ROAMING" VARCHAR2(32),"USAGE_TYPE" VARCHAR2(32),"COMPANY_CODE" VARCHAR2(32),"AMOUNT" NUMBER(16,2),"PERIOD" DATE)
CREATE TABLE "DCH_STAGING"("MONTH_TYPE" VARCHAR2(32),"BID" VARCHAR2(32),"TECHNOLOGY" VARCHAR2(32),"ROAMING" VARCHAR2(32),"USAGE_TYPE" VARCHAR2(32),"AMOUNT_EUR" NUMBER(16,2),"AMOUNT_USD" NUMBER(16,2),"COMPANY_CODE" VARCHAR2(12),"PERIOD" DATE)
CREATE TABLE "APRM_STAGING"("MONTH_TYPE" VARCHAR2(32),"BID" VARCHAR2(32),"TECHNOLOGY" VARCHAR2(32),"ROAMING" VARCHAR2(32),"USAGE_TYPE" VARCHAR2(32),"AMOUNT_EUR" NUMBER(16,2),"AMOUNT_USD" NUMBER(16,2),"COMPANY_CODE" VARCHAR2(64),"PERIOD" DATE)

INSERT INTO ENTERPRISE_GEN_SANDBOX.FILE_SUMMARY (USAGE_TYPE, TOTAL_VOLUME_DCH, TOTAL_VOLUME, TOTAL_RECORDS_DCH, TOTAL_RECORDS, TOTAL_CHARGES_DCH, 
   TOTAL_CHARGES, TC_SEND, SENDER, REJECTED_COUNT, REJECTED_CHARGES, RECEIVER, PROCESS_DATE, IDENTIFIER, FILE_TYPE, FILE_NAME_DCH, FILE_NAME, DUPLICATES, 
   DROPPED_TC, DROPPED_RECORDS, DROPPED_APRM_CHARGES, DROPPED_APRM, APRM_TOTAL_RECORDS, APRM_TOTAL_CHARGES, APRM_DIFFERENCE) 
VALUES ( 
 /* USAGE_TYPE */,
 /* TOTAL_VOLUME_DCH */,
 /* TOTAL_VOLUME */,
 /* TOTAL_RECORDS_DCH */,
 /* TOTAL_RECORDS */,
 /* TOTAL_CHARGES_DCH */,
 /* TOTAL_CHARGES */,
 /* TC_SEND */,
 /* SENDER */,
 /* REJECTED_COUNT */,
 /* REJECTED_CHARGES */,
 /* RECEIVER */,
 /* PROCESS_DATE */,
 /* IDENTIFIER */,
 /* FILE_TYPE */,
 /* FILE_NAME_DCH */
 /* FILE_NAME */,
 /* DUPLICATES */,
 /* DROPPED_TC */,
 /* DROPPED_RECORDS */,
 /* DROPPED_APRM_CHARGES */,
 /* DROPPED_APRM */,
 /* APRM_TOTAL_RECORDS */,
 /* APRM_TOTAL_CHARGES */,
 /* APRM_DIFFERENCE */ 
);


INSERT INTO ENTERPRISE_GEN_SANDBOX.REJECTED_RECORDS (
   TOTAL_CHARGE, FILE_NAME, ERROR_TYPE, ERROR_DESCRIPTION, ERROR_CODE) 
VALUES ( 
 /* TOTAL_CHARGE */,
 /* FILE_NAME */,
 /* ERROR_TYPE */,
 /* ERROR_DESCRIPTION */,
 /* ERROR_CODE */ 
);


INSERT INTO ENTERPRISE_GEN_SANDBOX.APRM (
   USAGE_TYPE, TOTAL_VOLUME_DCH, TOTAL_VOLUME, 
   TOTAL_CHARGES_DCH, TOTAL_CHARGES, SERVE_BID, 
   RECORD_COUNT_DCH, RECORD_COUNT, MARKET_CODE, 
   FILE_TYPE, DATE_PROCESSED, CLEARINGHOUSE, 
   CARRIER_CODE, BP_START_DATE) 
VALUES ( 
 /* USAGE_TYPE */,
 /* TOTAL_VOLUME_DCH */,
 /* TOTAL_VOLUME */,
 /* TOTAL_CHARGES_DCH */,
 /* TOTAL_CHARGES */,
 /* SERVE_BID */
 /* RECORD_COUNT_DCH */,
 /* RECORD_COUNT */,
 /* MARKET_CODE */,
 /* FILE_TYPE */,
 /* DATE_PROCESSED */,
 /* CLEARINGHOUSE */,
 /* CARRIER_CODE */,
 /* BP_START_DATE */ );


INSERT INTO ENTERPRISE_GEN_SANDBOX.DCH_INFO (
   USAGE_TYPE, TOTAL_VOLUME, TOTAL_RECORDS, 
   TOTAL_DURATION, TOTAL_CHARGES, THEIR_SID, 
   THEIR_CARRIER_NAME, SETTLEMENT_DATE, SEQUENCE_NUMBER, 
   ROAMING_TYPE, PROCESS_DATE, MY_SID, 
   MY_CARRIER_NAME, FILE_NAME, CALL_TYPE) 
VALUES ( /* USAGE_TYPE */,
 /* TOTAL_VOLUME */,
 /* TOTAL_RECORDS */,
 /* TOTAL_DURATION */,
 /* TOTAL_CHARGES */
 /* THEIR_SID */,
 /* THEIR_CARRIER_NAME */,
 /* SETTLEMENT_DATE */,
 /* SEQUENCE_NUMBER */,
 /* ROAMING_TYPE */,
 /* PROCESS_DATE */,
 /* MY_SID */,
 /* MY_CARRIER_NAME */,
 /* FILE_NAME */,
 /* CALL_TYPE */ );


INSERT INTO ENTERPRISE_GEN_SANDBOX.SAP_STAGING (
   USAGE_TYPE, TECHNOLOGY, ROAMING, 
   PERIOD, MONTH_TYPE, DOC_HEADER, 
   COMPANY_CODE, AMOUNT) 
VALUES ( /* USAGE_TYPE */,
 /* TECHNOLOGY */,
 /* ROAMING */,
 /* PERIOD */
 /* MONTH_TYPE */,
 /* DOC_HEADER */,
 /* COMPANY_CODE */,
 /* AMOUNT */ );


INSERT INTO ENTERPRISE_GEN_SANDBOX.DCH_STAGING (
   USAGE_TYPE, TECHNOLOGY, ROAMING, 
   PERIOD, MONTH_TYPE, COMPANY_CODE, 
   BID, AMOUNT_USD, AMOUNT_EUR) 
VALUES ( /* USAGE_TYPE */,
 /* TECHNOLOGY */,
 /* ROAMING */,
 /* PERIOD */
 /* MONTH_TYPE */,
 /* COMPANY_CODE */,
 /* BID */,
 /* AMOUNT_USD */,
 /* AMOUNT_EUR */ );


INSERT INTO ENTERPRISE_GEN_SANDBOX.APRM_STAGING (
   USAGE_TYPE, TECHNOLOGY, ROAMING, 
   PERIOD, MONTH_TYPE, COMPANY_CODE, 
   BID, AMOUNT_USD, AMOUNT_EUR) 
VALUES ( /* USAGE_TYPE */,
 /* TECHNOLOGY */,
 /* ROAMING */,
 /* PERIOD */
 /* MONTH_TYPE */,
 /* COMPANY_CODE */,
 /* BID */,
 /* AMOUNT_USD */,
 /* AMOUNT_EUR */ );



