#! /usr/local/bin/perl

$Market = "KPR01BCH02";
$market = lc($Market);

#$ENV{'OP_JOB_NAME'} = 'MPSBOOT';
#$ENV{'OP_ORA_INST'} = 'pc1'.$market;
#$ENV{'OP_ORA_USER'} = $market.'operconn';
#$ENV{'OP_ORA_PASS'} = $market.'operconn';

$mainPgm = "com.uscc.monitor.MpsMonitor";
$java = "/apps/amdocs/jdk1.8.0_131/bin/java";
$classpath = "./xmlParserAPIs.jar:./MpsMonitors.jar:./xercesImpl.jar:./xml-apis.jar";
# runs in a posix shell
$hh = "$java  -classpath $classpath $mainPgm $Market ./monitor.xml >mon.err 2>&1 &";

print "$hh \n";

exec($hh);

