SELECT FILE_NAME, 
       WR_REC_QUANTITY 
FROM AC_PROCESSING_ACCOUNTING 
WHERE FPFC_CUR_FILE_ALIAS IN ('AAA','QIS','PMG') 
AND   FPFC_CUR_PGM_NAME = 'MAF2COLL' 
AND   FPFC_NXT_PGM_NAME = 'MAF2COLL' 
AND   FPFC_NXT_FILE_ALIAS = 'TRNSFER'
AND   FILE_STATUS = 'CO' 
AND   DATA_GROUP != 'MARS' 
AND   FILE_PROCESS_DATE BETWEEN SYSDATE-?/24 AND SYSDATE-?/24