 SynthDef(\CavVol, {arg bufnum = 0,out = 0, midi = 33, gate = 1, amp = 2, bal = 0;
     var x,z,i,j,q;
     i = midi.midicps/55.00;
     q = Env.asr(2,1, 4, 1);
     q = EnvGen.kr(q, gate,doneAction:2);
     x = PlayBuf.ar(2, bufnum, BufRateScale.kr(bufnum)*i,1,0,0,  loop:1,doneAction:2);
     x = (x*((0.25*SinOsc.kr((0.125/2.0), 0, 0.5))+ 0.5));
     x = x * q;
     //	 x = x * gate;
     z = Balance2.ar(x[0],x[1], bal);
     Out.ar(out,z)}).store;