#! /usr/bin/perl

$Market = "KPR01EBIAP";
$market = lc($Market);


$mainPgm = "com.uscc.monitor.MpsMonitor";
$java = "/usr/java/jdk1.6.0_30/bin/java";
$classpath = "./xmlParserAPIs.jar:./MpsMonitors.jar:./xercesImpl.jar:./xerces.jar";
# runs in a posix shell
$hh = "$java  -classpath $classpath $mainPgm $Market ./monitor.xml >mon.err 2>&1 &";

print "$hh \n";

exec($hh);

