#! /usr/local/bin/perl

$Market = "KPRL6EVENT";
$market = lc($Market);

#$ENV{'OP_JOB_NAME'} = 'MPSBOOT';
#$ENV{'OP_ORA_INST'} = 'pc1'.$market;
#$ENV{'OP_ORA_USER'} = $market.'operconn';
#$ENV{'OP_ORA_PASS'} = $market.'operconn';

$mainPgm = "com.uscc.monitor.MpsMonitor";
$java = "/usr/java/jdk1.6.0_24/bin/java";
$classpath = "./xmlParserAPIs.jar:./MpsMonitors.jar:./xercesImpl.jar:./xerces.jar";
# runs in a posix shell
$hh = "$java -Xms64m -Xmx256m -classpath $classpath $mainPgm $Market ./monitor.xml >mon.err 2>&1 &";

print "$hh \n";

exec($hh);

