#! /usr/bin/perl

$Market = "KPR01EVE05";
$market = lc($Market);

$mainPgm = "com.uscc.monitor.MpsMonitor";
$java = "/apps/amdocs/jdk1.8.0_131/bin/java";
$classpath = "./xmlParserAPIs.jar:./MpsMonitors.jar:./xercesImpl.jar:./xml-apis.jar";
# runs in a posix shell
$hh = "$java -Xms64m -Xmx256m -classpath $classpath $mainPgm $Market ./monitor.xml >mon.err 2>&1 &";

print "$hh \n";

exec($hh);

