/* Formatted on 2/3/2020 9:59:24 AM (QP5 v5.300) */
SELECT CUSTOMER_ID,
       RESOURCE_VALUE,
       SYS_CREATION_DATE,
       L9_SYSTEM_SERVICE,
       L3_DURATION,
       L3_ROUNDED_UNIT,
       L3_CHARGE_AMOUNT,
       L3_CALL_DIRECTION,
       L9_ROAMING_IND,
       L9_CALLING_NUMBER,
       L9_CALLED_NUMBER,
       SERVICE_FILTER,
       L9_DIALED_DIGITS,
       L9_TOLL_DURATION,
       L9_BALANCE_AMOUNT,
       L9_DAILY_SURCHARGE_IND
  FROM APE1_RATED_EVENT A
 WHERE     1 = 1
       AND EVENT_TYPE_ID = 62
       AND L3_DURATION > 100
       AND L9_SESSION_IDENTIFIER LIKE 'RO_CTS%'
       AND SYS_CREATION_DATE > SYSDATE - 1
