SELECT /*+ Parallel (T1,16) */
 TO_CHAR (SYS_CREATION_DATE, 'YYYYMMDDHH24') "Date", COUNT (*)
    FROM APE1_RATED_EVENT
   WHERE SYS_CREATION_DATE >= '19-JAN-2020'
         AND SYS_CREATION_DATE < '20-JAN-2020'
         AND EVENT_TYPE_ID = 62
         AND L9_IS_ONLINE = 'Y'
GROUP BY TO_CHAR (SYS_CREATION_DATE, 'YYYYMMDDHH24')
ORDER BY TO_CHAR (SYS_CREATION_DATE, 'YYYYMMDDHH24')