#! /bin/sh

export UTLITIES_HOME=/apps/ebi/ebiap1/bin/usageUtlities/

cd ${UTLITIES_HOME}/work

mkdir -p mms

cat ../data/mms.dat | cut -f 1,2 | ../lib/bin/sumBy.py > mms/all_mms
../lib/bin/makePicSeries.pl -o mms/01_all_mms -i  mms/all_mms -s 1 -c "MMS Records" -t "All MMS for past 90 Days"
