#! /bin/sh

export UTLITIES_HOME=/home/dbalchen/workspace/usageUtlities

cd ${UTLITIES_HOME}/work

rm -fr data

mkdir ${UTLITIES_HOME}/work/data

cat ../data/data.dat | cut -f 1,2 | ../lib/bin/sumBy.py > data/all_dataRecs
../lib/bin/makePicSeries.pl -o data/all_dataRecs -i  data/all_dataRecs -s 1 -c "Data Records" -t "All Data for past 90 Days"

cat ../data/data.dat | grep POST | cut -f 1,2 | ../lib/bin/sumBy.py > data/all_post_dataRecs

../lib/bin/makePicSeries.pl -o data/all_post_dataRecs -i  data/all_post_dataRecs -s 1 -c "Data Records" -t "All Post Paid Data for past 90 Days"

cat ../data/data.dat | grep PRE | cut -f 1,2 | ../lib/bin/sumBy.py > data/all_pre_dataRecs

../lib/bin/makePicSeries.pl -o data/all_pre_dataRecs -i  data/all_pre_dataRecs -s 1 -c "Data Records" -t "All Pre Paid Data for past 90 Days"

# Home and Roam

mkdir -p data/home
mkdir -p data/roam

cat ../data/data.dat | grep POST | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > data/home/all_post_home_dataRecs

../lib/bin/makePicSeries.pl -o data/home/all_post_home_dataRecs -i  data/home/all_post_home_dataRecs -s 1 -c "Data Records" -t "All Home Post Paid Data for past 90 Days"

cat ../data/data.dat | grep PRE | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > data/home/all_pre_home_dataRecs

../lib/bin/makePicSeries.pl -o data/home/all_pre_home_dataRecs -i  data/home/all_pre_home_dataRecs -s 1 -c "Data Records" -t "All Home Pre Paid Data for past 90 Days"


cat ../data/data.dat | grep POST | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > data/roam/all_post_roam_dataRecs

../lib/bin/makePicSeries.pl -o data/roam/all_post_roam_dataRecs -i  data/roam/all_post_roam_dataRecs -s 1 -c "Data Records" -t "All Roam Post Paid Data for past 90 Days"

cat ../data/data.dat | grep PRE | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > data/roam/all_pre_roam_dataRecs

../lib/bin/makePicSeries.pl -o data/roam/all_pre_roam_dataRecs -i  data/roam/all_pre_roam_dataRecs -s 1 -c "Data Records" -t "All Roam Pre Paid Data for past 90 Days"

# 4G
mkdir -p data/4G

cat ../data/data.dat | grep 4G | cut -f 1,2 | ../lib/bin/sumBy.py > data/4G/all_4gdataRecs

../lib/bin/makePicSeries.pl -o data/4G/4Gall_dataRecs -i  data/4G/all_4gdataRecs -s 1 -c "Data Records" -t "All 4G Data for past 90 Days"

cat ../data/data.dat | grep 4G | grep POST | cut -f 1,2 | ../lib/bin/sumBy.py > data/4G/all_4gpost_dataRecs

../lib/bin/makePicSeries.pl -o data/4G/all_4gpost_dataRecs -i  data/4G/all_4gpost_dataRecs -s 1 -c "Data Records" -t "All 4G Post Paid Data for past 90 Days"

cat ../data/data.dat | grep 4G | grep PRE | cut -f 1,2 | ../lib/bin/sumBy.py > data/4G/all_4gpre_dataRecs

../lib/bin/makePicSeries.pl -o data/4G/4Gall_pre_dataRecs -i  data/4G/all_4gpre_dataRecs -s 1 -c "Data Records" -t "All 4G Pre Paid Data for past 90 Days"

mkdir -p data/4G/home
mkdir -p data/4G/roam

# Home and Roam

cat ../data/data.dat | grep 4G | grep POST | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > data/4G/home/all_4gpost_home_dataRecs

../lib/bin/makePicSeries.pl -o data/4G/home/4Gall_post_home_dataRecs -i  data/4G/home/all_4gpost_home_dataRecs -s 1 -c "Data Records" -t "All 4G Home Post Paid Data for past 90 Days"

cat ../data/data.dat | grep 4G | grep PRE | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > data/4G/home/all_4gpre_home_dataRecs

../lib/bin/makePicSeries.pl -o data/4G/home/all_4gpre_home_dataRecs -i  data/4G/home/all_4gpre_home_dataRecs -s 1 -c "Data Records" -t "All 4G Home Pre Paid Data for past 90 Days"


cat ../data/data.dat | grep 4G | grep POST | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > data/4G/roam/all_4gpost_roam_dataRecs

../lib/bin/makePicSeries.pl -o data/4G/roam/all_4gpost_roam_dataRecs -i  data/4G/roam/all_4gpost_roam_dataRecs -s 1 -c "Data Volume / TB" -t "All 4G Roam Post Paid Data for past 90 Days"

cat ../data/data.dat | grep 4G | grep PRE | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > data/4G/roam/all_4gpre_roam_dataRecs

../lib/bin/makePicSeries.pl -o data/4G/roam/all_4gpre_roam_dataRecs -i  data/4G/roam/all_4gpre_roam_dataRecs -s 1 -c "Data Records" -t "All 4G Roam Pre Paid Data for past 90 Days"

# 3G

mkdir -p data/3G/

cat ../data/data.dat | grep -v 4G | cut -f 1,2 | ../lib/bin/sumBy.py > data/3G/all_3gdataRecs

../lib/bin/makePicSeries.pl -o data/3G/3Gall_dataRecs -i  data/3G/all_3gdataRecs -s 1 -c "Data Records" -t "All 3G Data for past 90 Days"

cat ../data/data.dat | grep -v 4G | grep POST | cut -f 1,2 | ../lib/bin/sumBy.py > data/3G/all_3gpost_dataRecs

../lib/bin/makePicSeries.pl -o data/3G/3Gall_post_dataRecs -i  data/3G/all_3gpost_dataRecs -s 1 -c "Data Records" -t "All 3G Post Paid Data for past 90 Days"

cat ../data/data.dat | grep -v 4G | grep PRE | cut -f 1,2 | ../lib/bin/sumBy.py > data/3G/all_3gpre_dataRecs

../lib/bin/makePicSeries.pl -o data/3G/3Gall_pre_dataRecs -i  data/3G/all_3gpre_dataRecs -s 1 -c "Data Records" -t "All 3G Pre Paid Data for past 90 Days"

# Home and Roam

mkdir -p data/3G/home/
mkdir -p data/3G/roam/

cat ../data/data.dat | grep -v 4G | grep POST | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > data/3G/home/all_3gpost_home_dataRecs

../lib/bin/makePicSeries.pl -o data/3G/home/3Gall_post_home_dataRecs -i  data/3G/home/all_3gpost_home_dataRecs -s 1 -c "Data Records" -t "All 3G Home Post Paid Data for past 90 Days"

cat ../data/data.dat | grep -v 4G | grep PRE | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > data/3G/home/all_3gpre_home_dataRecs

../lib/bin/makePicSeries.pl -o data/3G/home/3Gall_pre_home_dataRecs -i  data/3G/home/all_3gpre_home_dataRecs -s 1 -c "Data Records" -t "All 3G Home Pre Paid Data for past 90 Days"


cat ../data/data.dat | grep -v 4G | grep POST | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > data/3G/roam/all_3gpost_roam_dataRecs

../lib/bin/makePicSeries.pl -o data/3G/roam/3Gall_post_roam_dataRecs -i  data/3G/roam/all_3gpost_roam_dataRecs -s 1 -c "Data Records" -t "All 3G Roam Post Paid Data for past 90 Days"

cat ../data/data.dat | grep -v 4G | grep PRE | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > data/3G/roam/all_3gpre_roam_dataRecs

../lib/bin/makePicSeries.pl -o data/3G/roam/3Gall_pre_roam_dataRecs -i  data/3G/roam/all_3gpre_roam_dataRecs -s 1 -c "Data Records" -t "All 3G Roam Pre Paid Data for past 90 Days"
