#! /bin/sh

export UTLITIES_HOME=/apps/ebi/ebiap1/bin/usageUtlities/

cd ${UTLITIES_HOME}/work

mkdir -p voice/
mkdir -p voice/home
mkdir -p voice/roam

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | cut -f 1,3 | ../lib/bin/sumBy.py > voice/all_voice
../lib/bin/makePicSeries.pl -o voice/01_all_voice -i  voice/all_voice -s 0.0166666666666667 -c "Voice Volume / Minutes" -t "All Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep N | cut -f 1,3 | ../lib/bin/sumBy.py > voice/home/all_home_voice
../lib/bin/makePicSeries.pl -o voice/home/02_all_home_voice -i  voice/home/all_home_voice -s 0.0166666666666667 -c "Voice Home Volume / Minutes" -t "All Home Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep Y | cut -f 1,3 | ../lib/bin/sumBy.py > voice/roam/all_roam_voice
../lib/bin/makePicSeries.pl -o voice/roam/03_all_roam_voice -i  voice/roam/all_roam_voice -s 0.0166666666666667 -c "Voice Roam Volume / Minutes" -t "All Roam Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep POST| cut -f 1,3 | ../lib/bin/sumBy.py > voice/all_post_voice
../lib/bin/makePicSeries.pl -o voice/04_all_post_voice -i  voice/all_post_voice -s 0.0166666666666667 -c "Post Voice Volume / Minutes" -t "All Post Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep N | grep POST| cut -f 1,3 | ../lib/bin/sumBy.py > voice/home/all_post_home_voice
../lib/bin/makePicSeries.pl -o voice/home/05_all_post_home_voice -i  voice/home/all_post_home_voice -s 0.0166666666666667 -c "Voice Post Home Volume / Minutes" -t "All Post Home Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep Y | grep POST| cut -f 1,3 | ../lib/bin/sumBy.py > voice/all_post_roam_voice
../lib/bin/makePicSeries.pl -o voice/06_all_post_roam_voice -i  voice/all_post_roam_voice -s 0.0166666666666667 -c "Voice Roam Volume / Minutes" -t "All Post Roam Voice for past 90 Days"


cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep PRE| cut -f 1,3 | ../lib/bin/sumBy.py > voice/all_pre_voice
../lib/bin/makePicSeries.pl -o voice/07_all_pre_voice -i  voice/all_pre_voice -s 0.0166666666666667 -c "PRE Voice Volume / Minutes" -t "All PRE Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep N | grep PRE| cut -f 1,3 | ../lib/bin/sumBy.py > voice/home/all_pre_home_voice
../lib/bin/makePicSeries.pl -o voice/home/08_all_pre_home_voice -i  voice/home/all_pre_home_voice -s 0.0166666666666667 -c "Voice PrePaid Home Volume / Minutes" -t "All Post Home Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep Y | grep PRE| cut -f 1,3 | ../lib/bin/sumBy.py > voice/roam/all_pre_roam_voice
../lib/bin/makePicSeries.pl -o voice/roam/09_all_pre_roam_voice -i  voice/roam/all_pre_roam_voice -s 0.0166666666666667 -c "Voice PrePaid Roam Volume / Minutes" -t "All Post Roam Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep tas | cut -f 1,3 | ../lib/bin/sumBy.py > voice/all_volte_voice
../lib/bin/makePicSeries.pl -o voice/10_all_volte_voice -i  voice/all_volte_voice -s 0.0166666666666667 -c "All VoLTE Volume / Minutes" -t "All VoLTE for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep tas | grep N | cut -f 1,3 | ../lib/bin/sumBy.py > voice/home/all_volte_home_voice
../lib/bin/makePicSeries.pl -o voice/home/11_all_volte_home_voice -i  voice/home/all_volte_home_voice -s 0.0166666666666667 -c "All VoLTE Home Volume / Minutes" -t "All VoLTE Home for the past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep tas | grep Y | cut -f 1,3 | ../lib/bin/sumBy.py > voice/roam/all_volte_roam_voice
../lib/bin/makePicSeries.pl -o voice/roam/12_all_volte_roam_voice -i  voice/roam/all_volte_roam_voice -s 0.0166666666666667 -c "All VoLTE Roam Volume / Minutes" -t "All VoLTE Roam for the past 90 Days"

cat ../data/voice.dat | egrep  'VCDM|VLTE' | grep PRE | cut -f 1,3 | ../lib/bin/sumBy.py| tail -60 > voice/all_prepay_volte
../lib/bin/makePicSeries.pl -o voice/12_all_prepay_volte -i  voice/all_prepay_volte -s 0.0166666666666667 -c "All Prepay VoLTE Volume / Minutes" -t " All Prepay VoLTE the past 60 Days"
