#! /bin/sh

export UTLITIES_HOME=/home/dbalchen/workspace/usageUtlities/

cd ${UTLITIES_HOME}/work

mkdir -p voice/
mkdir -p voice/home
mkdir -p voice/roam

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | cut -f 1,2 | ../lib/bin/sumBy.py > voice/all_voiceRecs
../lib/bin/makePicSeries.pl -o voice/01_all_voiceRecs -i  voice/all_voiceRecs -s 1 -c "Voice Records" -t "All Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > voice/home/all_home_voiceRecs
../lib/bin/makePicSeries.pl -o voice/home/02_all_home_voiceRecs -i  voice/home/all_home_voiceRecs -s 1 -c "Voice Home Records" -t "All Home Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > voice/roam/all_roam_voiceRecs
../lib/bin/makePicSeries.pl -o voice/roam/03_all_roam_voiceRecs -i  voice/roam/all_roam_voiceRecs -s 1 -c "Voice Roam Records" -t "All Roam Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep POST| cut -f 1,2 | ../lib/bin/sumBy.py > voice/all_post_voiceRecs
../lib/bin/makePicSeries.pl -o voice/04_all_post_voiceRecs -i  voice/all_post_voiceRecs -s 1 -c "Post Voice Records" -t "All Post Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep N | grep POST| cut -f 1,2 | ../lib/bin/sumBy.py > voice/home/all_post_home_voiceRecs
../lib/bin/makePicSeries.pl -o voice/home/05_all_post_home_voiceRecs -i  voice/home/all_post_home_voiceRecs -s 1 -c "Voice Post Home Records" -t "All Post Home Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep Y | grep POST| cut -f 1,2 | ../lib/bin/sumBy.py > voice/all_post_roam_voiceRecs
../lib/bin/makePicSeries.pl -o voice/06_all_post_roam_voiceRecs -i  voice/all_post_roam_voiceRecs -s 1 -c "Voice Roam Records" -t "All Post Roam Voice for past 90 Days"


cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep PRE| cut -f 1,2 | ../lib/bin/sumBy.py > voice/all_pre_voiceRecs
../lib/bin/makePicSeries.pl -o voice/07_all_pre_voiceRecs -i  voice/all_pre_voiceRecs -s 1 -c "PRE Voice Records" -t "All PRE Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep N | grep PRE| cut -f 1,2 | ../lib/bin/sumBy.py > voice/home/all_pre_home_voiceRecs
../lib/bin/makePicSeries.pl -o voice/home/08_all_pre_home_voiceRecs -i  voice/home/all_pre_home_voiceRecs -s 1 -c "Voice PrePaid Home Records" -t "All PRE Home Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep Y | grep PRE| cut -f 1,2 | ../lib/bin/sumBy.py > voice/roam/all_pre_roam_voiceRecs
../lib/bin/makePicSeries.pl -o voice/roam/09_all_pre_roam_voiceRecs -i  voice/roam/all_pre_roam_voiceRecs -s 1 -c "Voice PrePaid Roam Records" -t "All PRE Roam Voice for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep tas | cut -f 1,2 | ../lib/bin/sumBy.py > voice/all_volte_voiceRecs
../lib/bin/makePicSeries.pl -o voice/10_all_volte_voiceRecs -i  voice/all_volte_voiceRecs -s 1 -c "All VoLTE Records" -t "All VoLTE for past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep tas | grep N | cut -f 1,2 | ../lib/bin/sumBy.py > voice/home/all_volte_home_voiceRecs
../lib/bin/makePicSeries.pl -o voice/home/11_all_volte_home_voiceRecs -i  voice/home/all_volte_home_voiceRecs -s 1 -c "All VoLTE Home Records" -t "All VoLTE Home for the past 90 Days"

cat ../data/voice.dat | egrep -v 'VCDM|VLTE' | grep tas | grep Y | cut -f 1,2 | ../lib/bin/sumBy.py > voice/roam/all_volte_roam_voiceRecs
../lib/bin/makePicSeries.pl -o voice/roam/12_all_volte_roam_voiceRecs -i  voice/roam/all_volte_roam_voiceRecs -s 1 -c "All VoLTE Roam Records" -t "All VoLTE Roam for the past 90 Days"

cat ../data/voice.dat | egrep  'VCDM|VLTE' | grep PRE | cut -f 1,2 | ../lib/bin/sumBy.py| tail -60 > voice/all_prepay_volteRecs
../lib/bin/makePicSeries.pl -o voice/12_all_prepay_volteRecs -i  voice/all_prepay_volteRecs -s 1 -c "All Prepay VoLTE Records" -t " All PRE VoLTE the past 60 Days"
