#!/bin/ksh

PATH=".:/bin:${PATH}"
export PATH

# Now change to the directory containing all the Call Dump executables.
cd /home/calldmp/CallDump2.0/bin

#echo "/copyfiles.pl $1 ${2} "
#./copyfiles.pl /m01/switch_old/AAA /m01/switch/AAA >> ../log/copyprodfiles.log  2>&1
./copyfiles.pl /cares/mpsm01b/m01/projs/up/physical/switch/ /m01/switch/ >> ../log/copyprodfiles.log  2>&1 &
./copyfiles.pl /cares/mpsm02b/m02/projs/up/physical/switch/ /m02/switch/ >> ../log/copyprodfiles.log  2>&1 &
./copyfiles.pl /cares/mpsm03b/m03/projs/up/physical/switch/ /m03/switch/ >> ../log/copyprodfiles.log  2>&1 &
./copyfiles.pl /cares/mpsm04b/m04/projs/up/physical/switch/ /m04/switch/ >> ../log/copyprodfiles.log  2>&1 &
./copyfiles.pl /cares/mpsm05b/m05/projs/up/physical/switch/ /m05/switch/ >> ../log/copyprodfiles.log  2>&1 &
./copyfiles.pl /cares/mps2m06/m06/projs/up/physical/switch/ /m06/switch/ >> ../log/copyprodfiles.log  2>&1 &

if [ $? -ne 0 ]
then    
        echo "2"
        exit
fi

echo "0"

exit
