#! /usr/bin/perl

$Market = "KPR01OPRMN";
$market = lc($Market);


$mainPgm = "com.uscc.monitor.MpsMonitor";
$java = "/usr/java/java.current/bin/java";
$classpath = "./xml-apis.jar:./MpsMonitors.jar:./xercesImpl.jar:./xercesSamples.jar";
# runs in a posix shell
$hh = "$java  -classpath $classpath $mainPgm $Market ./monitor.xml >mon.err 2>&1 &";

print "$hh \n";

exec($hh);

