#! /usr/local/bin/perl

$Market = "KPR01BCH03";
$market = lc($Market);

$mainPgm = "com.uscc.monitor.MpsMonitor";
$java = "/apps/amdocs/jdk1.8.0_131/bin/java";
$classpath = "./xmlParserAPIs.jar:./MpsMonitors.jar:./xercesImpl.jar:./xml-apis.jar";
# runs in a posix shell
$hh = "$java  -classpath $classpath $mainPgm $Market ./monitor.xml > ./mon.err 2>&1 &";

print "$hh \n";

exec($hh);

