#Code Generated by ZenTest v. 4.1.4
#                 classname: asrt / meth =  ratio%
#                    Rhythm:    0 /    6 =   0.00%


require 'test/unit' unless defined? $ZENTEST and $ZENTEST

require 'Tools.rb'
require 'Motif.rb'
require 'Rhythm.rb'
require 'Notes.rb'
require 'Composition.rb'
require 'robo_comp.rb'
require 'Melody.rb'

class TestMelody < Test::Unit::TestCase
  
  def test_addTones2
    mycomp = load "/home/dbalchen/workspace/RoboComp/maribaT1.mid"
    
    pt = get 1
    
    pp = pt.clone
    
    pp = pp * 2
    
 #   play pp
    
    mycomp = load "/home/dbalchen/workspace/RoboComp/maribaT2.mid"
    
    ppp = get 1
    
    
 #   play ppp 
    
    p3 = ppp & pp
    
    play p3 | $mel
    
  end
  def test_addTones
    
    beat = Rhythm.new  
    pattern = beat.addBeats 7
    
    pattern = pattern + pattern + pattern + pattern
    #   play pattern
    
    mel = Melody.new
    
    pat2 = mel.addTones(pattern)
    
    play pat2
  end
  
  def test_makeSpline
    raise NotImplementedError, 'Need to write test_makeSpline'
  end
  
end

# Number of errors detected: 10
