# Code Generated by ZenTest v. 3.11.1
#                 classname: asrt / meth =  ratio%
#                  RoboComp:    0 /    7 =   0.00%
# Number of errors detected: 1
require 'robo_comp.rb'
require 'test/unit' unless defined? $ZENTEST and $ZENTEST
#require '../lib/robo_comp.rb'
#class Metronome
#  def initialize(bpm, midi)
#    @midi = midi
#    @midi.program_change(0, 115)
#    @interval = 60.0 / bpm
#    @timer = Timer.get(@interval/10)
#    now = Time.now.to_f
#    register_next_bang(now)
#  end
#  
#  def register_next_bang(time)
#    @timer.at(time) do |this_time|
#      register_next_bang(this_time + @interval)
#      bang
#    end
#  end
#
#  def bang
#    @midi.play(0, 84, 0.1, 100, Time.now.to_f)
#  end
#end

puts "Test"

load "/home/dbalchen/Music/Curve/melody.mid"
#p = Pitch.new("C","MINOR")
#$cmp.seed.tones = p
#$cmp.normalizeTracks
live false
#
#a = get 2
a = get 1
#a = a.clone
#b = b.clone
a = a.fixDur
#b = b.fixDur
#aa = a.get(1,2)
#aaa = a.get(3,4)
#
#bb = b.get(1,2)
#bbb = b.get(3,4)
#k = aaa.keepr

#c = (a.flatten(b.clear)) | $mel

a.pitchSet

play a

puts "Bye Bye"


