# Code Generated by ZenTest v. 3.11.1
#                 classname: asrt / meth =  ratio%
#                  RoboComp:    0 /    7 =   0.00%
# Number of errors detected: 1
require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'robo_comp.rb'

puts "Test"

clear

stuff = load "/home/dbalchen/workspace/RoboComp/BBugs.mid"

play stuff

stuff = load "/home/dbalchen/workspace/RoboComp/BirdsAndBugsChordOnly.mid"

play stuff

stuff = load "/home/dbalchen/workspace/RoboComp/BirdsAndBugs.mid"

play stuff

save "BirdsAndBugs"

clear

stuff = load "/home/dbalchen/workspace/RoboComp/BirdsAndBugs.rob"

play stuff 

