# Code Generated by ZenTest v. 4.1.4
#                 classname: asrt / meth =  ratio%
#                    Rhythm:    0 /    6 =   0.00%


require 'test/unit' unless defined? $ZENTEST and $ZENTEST

require 'Tools.rb'
require 'Motif.rb'
require 'Rhythm.rb'
require 'Notes.rb'
require 'Composition.rb'
require 'robo_comp.rb'

class TestRhythm < Test::Unit::TestCase
  def test_addBeats
    beat = Rhythm.new  
    pattern = beat.addBeats
    pattern2 = beat.addBeats 4
    play pattern2
    
    beat.maxSize = -1
    pattern3 = beat.addBeats 8
    play pattern3
    
    beat.maxSize = 21
    pattern4 = beat.addBeats 16
    play pattern4
  end
  
  def test_beats
    beat = Rhythm.new  
    pattern = beat.addBeats
    play pattern
    play pattern | beat.beats(6)
 
  end
  
  def test_basicBeat
   raise NotImplementedError, 'Need to write test_basicBeat'
  end
  
end
