# Code Generated by ZenTest v. 3.10.0
#                 classname: asrt / meth =  ratio%
#                     Beats:    0 /    4 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

require 'Tools.rb'
require 'Motif.rb'
require 'Rhythm.rb'
require 'Melody.rb'
require 'Notes.rb'
require 'Composition.rb'
require 'robo_comp.rb'

class TestBeats < Test::Unit::TestCase
#  def test_basic
#    raise NotImplementedError, 'Need to write test_basic'
#  end
#
#  def test_beatDefaults
#    raise NotImplementedError, 'Need to write test_beatDefaults'
#  end
#
#  def test_beatDefaults_equals
#    raise NotImplementedError, 'Need to write test_beatDefaults_equals'
#  end
#
#  def test_layered
#    raise NotImplementedError, 'Need to write test_layered'
#  end
#
#  def test_pattern
#    raise NotImplementedError, 'Need to write test_pattern'
#  end

 def test_beatMaker
   
   beat = Rhythm.new  
   melody = Melody.new
   pattern = beat.addBeats
   
   pattern = pattern | beat.beats(8, -1)

   
   pattern = pattern * 4
   pattern = melody.addTones(pattern)
   
#   pattern = (pattern | beat.beats(2, -1)) * 4
   
#   pattern = melody.addTones(pattern)
      play pattern
#   pattern2 = beat.addBeats 3
#   play pattern2
#   
#   beat.maxSize = -1
#   pattern3 = beat.addBeats 7
#   play pattern3
#   
#   beat.maxSize = 21
#   pattern4 = beat.addBeats 15
#   play pattern4
#   
#   puts pattern
#   puts pattern2
#   puts pattern3
#   
 end
 
 #def test_pattern
#   beat = Rhythm.new
#   
#   pat = beat.pattern 4
#   
#   puts pat
# end
end

# Number of errors detected: 6
